#!/bin/sh

# create m4 dir if not exist
if ! test -d m4; then
    mkdir m4;
fi

# Checks for subdirectory
if test ! -e libwxnkf/configure.ac; then
   echo "libwxnkf is not found. exec git submodule...";
   git submodule init;
   git submodule update;
fi

# exec autoreconf
autoreconf -vi -I`pwd`/m4